---
  - name: VPC | Creating an AWS VPC inside mentioned Region
    tags:
      - web
      - vpc
      - elb
    local_action: 
      module: ec2_vpc
      region: "{{ region }}"
      state: present
      dns_hostnames: yes
      dns_support: yes
      cidr_block: "{{ vpc_cidr_block }}"
      resource_tags:
        Name: "{{ vpc_name }}-vpc"
      subnets: "{{ vpc_subnets }}" 
      internet_gateway: yes
      route_tables: "{{ public_subnet_rt }}"
    register: vpc
 
  - name: VPC | Write vpc id to state file
    tags:
      - web
      - vpc
    local_action:
      module: ini_file
      dest: ./vpc-state
      section: vpc
      option: id
      value: "{{ vpc.vpc_id }}"

  - name: VPC | Write subnet ids to state file
    tags:
      - web
      - vpc
    local_action:
      module: ini_file
      dest: ./vpc-state
      section: "{{ item.az }}"
      option: subnet
      value: "{{ item.id }}"
    with_items: "{{ vpc.subnets }}"

  - name: VPC | Write public and private access to state file
    tags:
      - web
      - vpc
    local_action:
      module: ini_file
      dest: ./vpc-state
      section: "{{ item.az }}"
      option: access
      value: "{{ item.resource_tags.access }}"
    with_items: "{{ vpc.subnets }}"

  - name: VPC | Set the public and private subnet id as facts
    tags:
      - vpc
      - web
    set_fact:
      vpc_id: "{{ lookup('ini', 'id section=vpc file=./vpc-state') }}"
      public_subnet_1: "{{ lookup('ini', 'subnet section=' + region + 'a file=./vpc-state') }}"
      public_subnet_2: "{{ lookup('ini', 'subnet section=' + region + 'b file=./vpc-state') }}"
      private_subnet: "{{ lookup('ini', 'subnet section=' + region + 'c file=./vpc-state') }}"
