---
  - name: Web | create WEB security group
    tags: web
    local_action:
      module: ec2_group
      name: "{{ item.name }}"
      description: "{{ item.description }}"
      region: "{{ region }}"
      vpc_id: "{{ vpc.vpc_id }}"
      state: present
      rules: "{{ item.rules }}"
    with_items: "{{ web_security_groups }}"
    register: sg_web

  - name: Web | tag the WEB security group
    tags: web
    local_action:
      module: ec2_tag
      resource: "{{ item.group_id}}"
      region: "{{ vpc_region }}"
      state: present
      tags:
        Name: "{{ vpc_name }}-{{ item.item.name }}"
    with_items: "{{ sg_web.results }}"
  
  - name: Web | find ami
    tags: web
    ec2_ami_find:
      name: "ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-*"
      owner: 099720109477
      sort: creationDate
      sort_order: descending
      sort_end: 1
      region: "{{ region }}"
      virtualization_type: hvm
      no_result_action: fail
    register: find_ami

  - name: Web | setup ami variable
    tags: web
    set_fact:
      ami: "{{ find_ami.results[0].ami_id }}"

  - name: Web | create instances
    tags: web
    local_action:
      module: ec2
      region: "{{ region }}"
      group: "{{ web_security_groups[0].name }}"
      keypair: "{{ key_name }}"
      instance_type: "{{ web_instance_type }}"
      image: "{{ ami }}"
      vpc_subnet_id: "{{ item }}"
      id: "{{ application }}-{{ item }}-1"
      wait: True
      assign_public_ip: yes
      user_data: |
        #!/bin/sh
        sudo apt-get install nginx -y
      instance_tags:
        Name: "{{ vpc_name }}_web"
        Environment: "{{ ENV }}"
        Role: "{{ server_role }}"
        Application: "{{ application }}"
    with_items:
      - "{{ public_subnet_1 }}"
      # we only do one server due to missing nfs config
      # - "{{ public_subnet_2 }}"
    register: web

  - name: Web | extract instance ids
    set_fact:
      web_instances: "{{ web.results|map(attribute='instances')|map('first')|list }}"
      instances_created: "{{ web|changed }}"
    tags: web

  - name: Web | store instace public ip addresses to hosts file
    tags: web
    local_action:
      module: lineinfile
      dest: "{{ ENV }}"
      insertafter: '\[webserver\]'
      line: "{{ item.public_ip }}"
      regexp: "{{ item.public_ip }}"
    with_items: "{{ web_instances }}"

  - name: Web | wait for SSH to come up
    tags: web
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      timeout: 320
      state: started
    with_items: "{{ web_instances }}"
    when: instances_created

  - name: Create SSH Group to login dynamically to EC2 Instance(s)
    tags: web
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: webserver
    with_items: "{{ web_instances }}"
